apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: mern-client:latest
          imagePullPolicy: Never # Use local image since we're using Minikube
          ports:
            - containerPort: 80
