apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: mern-app
spec:
  selector:
    app: mern-client
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30009
  type: NodePort
