apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: mern-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mern-server
  template:
    metadata:
      labels:
        app: mern-server
    spec:
      containers:
        - name: mern-server
          image: mujtaba979/mern-server:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "5000"
            - name: MONGODB_URI
              value: "mongodb://mongodb-service:27017/mernapp"
          ports:
            - containerPort: 5000
