name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Clean workspace first
        run: |
          Remove-Item -Path * -Recurse -Force -ErrorAction SilentlyContinue
          
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false
          clean: false

      - name: Debug directory structure
        run: |
          echo "Listing repository structure:"
          dir
          echo "Checking for app directory:"
          if (Test-Path -Path "app") { dir app } else { echo "app directory does not exist" }
          echo "Checking for server directory:"
          if (Test-Path -Path "server") { echo "server directory exists" } else { echo "server directory not found" }

      - name: Set up Docker to use Minikube's environment
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Build Server Docker image
        run: |
          cd app/server
          # Create a simple Dockerfile if it doesn't exist
          if (-not (Test-Path -Path "Dockerfile")) {
            @"
FROM node:18-alpine
WORKDIR /app
COPY . .
RUN npm install
EXPOSE 5000
CMD ["node", "app.js"]
"@ | Out-File -FilePath "Dockerfile" -Encoding utf8
          }
          docker build -t mujtaba979/mern-server:latest .

      - name: Build Client Docker image
        run: |
          cd app/client
          # Create a simple Dockerfile if it doesn't exist
          if (-not (Test-Path -Path "Dockerfile")) {
            @"
FROM node:18-alpine as build
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
"@ | Out-File -FilePath "Dockerfile" -Encoding utf8
          }
          docker build -t mujtaba979/mern-client:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push mujtaba979/mern-server:latest
          docker push mujtaba979/mern-client:latest

      - name: Deploy to Minikube
        run: |
          kubectl create namespace mern-app --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/server-deployment.yaml -n mern-app
          kubectl apply -f k8s/server-service.yaml -n mern-app
          kubectl apply -f k8s/client-deployment.yaml -n mern-app
          kubectl apply -f k8s/client-service.yaml -n mern-app
