name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug - Display current directory and contents
        run: |
          echo "Current directory: $(pwd)"
          find . -maxdepth 3

      - name: Debug - Display server directory contents
        run: |
          echo "Server directory contents:"
          ls -la ./app/server || echo "Directory not found"

      - name: Debug - Cat Dockerfile content (if exists)
        run: |
          if [ -f ./app/server/Dockerfile ]; then
            cat ./app/server/Dockerfile
          else
            echo "Dockerfile not found"
          fi

      - name: Set up Docker to use Minikube's environment
        run: |
          eval $(minikube -p minikube docker-env)

      - name: Build server image
        run: |
          cd ./app/server
          docker build -t mujtaba979/mern-server:latest .

      - name: Build client image
        run: |
          cd ./app/client
          docker build -t mujtaba979/mern-client:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push mujtaba979/mern-server:latest
          docker push mujtaba979/mern-client:latest

      - name: Deploy to Minikube
        run: |
          kubectl create namespace mern-app --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/mongodb-deployment.yaml -n mern-app
          kubectl apply -f k8s/server-deployment.yaml -n mern-app
          kubectl apply -f k8s/server-service.yaml -n mern-app
          kubectl apply -f k8s/client-deployment.yaml -n mern-app
          kubectl apply -f k8s/client-service.yaml -n mern-app
