name: Build and Deploy to Minikube

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker to use Minikube's environment
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          & minikube -p minikube docker-env --shell powershell | Invoke-Expression

      - name: Build Server Docker image
        run: |
          cd server
          docker build -t mujtaba979/mern-server:latest .

      - name: Build Client Docker image
        run: |
          cd client
          docker build -t mujtaba979/mern-client:latest .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images to Docker Hub
        run: |
          docker push mujtaba979/mern-server:latest
          docker push mujtaba979/mern-client:latest

      - name: Deploy to Minikube
        run: |
          kubectl create namespace mern-app --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -f k8s/server-deployment.yaml -n mern-app
          kubectl apply -f k8s/server-service.yaml -n mern-app
          kubectl apply -f k8s/client-deployment.yaml -n mern-app
          kubectl apply -f k8s/client-service.yaml -n mern-app

      - name: Verify deployment status
        run: |
          kubectl get pods -n mern-app
          kubectl get services -n mern-app
